// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtQvhdVqy258igCVSByKNwF9oxBN4bc7A',
    appId: '1:121012062157:web:391b779e0b8006e62f6684',
    messagingSenderId: '121012062157',
    projectId: 'todoapp-7d95c',
    authDomain: 'todoapp-7d95c.firebaseapp.com',
    storageBucket: 'todoapp-7d95c.appspot.com',
    measurementId: 'G-GMZ5BPY7KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBHKxMa39987lt-Y2jEPpsfwtSVr8KeeM',
    appId: '1:121012062157:android:cbf57cf8f973a6b62f6684',
    messagingSenderId: '121012062157',
    projectId: 'todoapp-7d95c',
    storageBucket: 'todoapp-7d95c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6VLDJSuUJg9H6Fwv94qGu9V7TqgNNcNQ',
    appId: '1:121012062157:ios:76de8b25baf551b42f6684',
    messagingSenderId: '121012062157',
    projectId: 'todoapp-7d95c',
    storageBucket: 'todoapp-7d95c.appspot.com',
    iosClientId: '121012062157-6i886a31nek2k59noh0ssi9lreqg76hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6VLDJSuUJg9H6Fwv94qGu9V7TqgNNcNQ',
    appId: '1:121012062157:ios:76de8b25baf551b42f6684',
    messagingSenderId: '121012062157',
    projectId: 'todoapp-7d95c',
    storageBucket: 'todoapp-7d95c.appspot.com',
    iosClientId: '121012062157-6i886a31nek2k59noh0ssi9lreqg76hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
